import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Head from "../../node_modules/next/head";
import Script from "../../node_modules/next/script";

// Local fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <meta name="google-adsense-account" content="ca-pub-7818225422285491"/>
      </Head>
        <Script async src={`https://pagead2.googlesyndication.com /pagead/js/adsbygoogle.js?client=${process.env.NEXT_PUBLIC}`} crossOrigin={`anonymous`} strategy={`afterInteractive`} ></Script>

      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-white`}
        >
        <Navbar />
        <ins
      className="adsbygoogle"
      style={{ display: "block" }}
      data-ad-client={client}
      data-ad-slot={slot}
      data-ad-format={format}
      data-full-width-responsive={responsive}
    ></ins>
        {children}
      </body>
    </html>
  );
};