import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Head from "../../node_modules/next/head";
import Script from "../../node_modules/next/script";

// Local fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

        <Script async src={`https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=${process.env.NEXT_PUBLIC}`} crossOrigin={`anonymous`} strategy={`afterInteractive`} ></Script>

      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-white`}
        >
        <Navbar />
        {children}
      </body>
    </html>
  );
};