import connectDB from "../../../../../config/database";
import DashboardModel from "../../../../../models/dashboardModel";
import { NextResponse } from "next/server";


export function getStaticProps() {
    return {
        props: {
        title: "Create Next App",
        description: "Generated by create next app",
        },
    };
}

export async function GET(req, { params }) {
  try {
      await connectDB();
      const {sort} = params;
      const data = await DashboardModel.find({ sort: sort });
      return NextResponse.json({ data }, {
          status: 200,
          headers: {
              'Content-Type': 'application/json',
              'Cache-Control': 'no-cache, must-revalidate, proxy-revalidate',
              'Pragma': 'no-cache, must-revalidate, proxy-revalidate',
              'Expires': '0',
              'Surrogate-Control': 'no-cache, must-revalidate, proxy-revalidate'
            },
      });
  } catch (error) {
      return NextResponse.json({ message: 'Internal Server Error' }, {
          status: 500,
          headers: { 'Content-Type': 'application/json' },
      });
  }
}

